export const phoneCodes = [
  { label: "Afghanistan", value: "af-93" },
  { label: "Albania", value: "al-355" },
  { label: "Algeria", value: "dz-213" },
  { label: "Andorra", value: "ad-376" },
  { label: "Angola", value: "ao-244" },
  { label: "Antigua and Barbuda", value: "ag-1268" },
  { label: "Argentina", value: "ar-54" },
  { label: "Armenia", value: "am-374" },
  { label: "Aruba", value: "aw-297" },
  { label: "Australia", value: "au-61" },
  { label: "Austria", value: "at-43" },
  { label: "Azerbaijan", value: "az-994" },
  { label: "Bahamas", value: "bs-1242" },
  { label: "Bahrain", value: "bh-973" },
  { label: "Bangladesh", value: "bd-880" },
  { label: "Barbados", value: "bb-1246" },
  { label: "Belarus", value: "by-375" },
  { label: "Belgium", value: "be-32" },
  { label: "Belize", value: "bz-501" },
  { label: "Benin", value: "bj-229" },
  { label: "Bermuda", value: "bm-1441" },
  { label: "Bhutan", value: "bt-975" },
  { label: "Bolivia", value: "bo-591" },
  { label: "Bosnia and Herzegovina", value: "ba-387" },
  { label: "Botswana", value: "bw-267" },
  { label: "Brazil", value: "br-55" },
  { label: "British Virgin Islands", value: "vg-1284" },
  { label: "Brunei", value: "bn-673" },
  { label: "Bulgaria", value: "bg-359" },
  { label: "Burkina Faso", value: "bf-226" },
  { label: "Burundi", value: "bi-257" },
  { label: "Cabo Verde", value: "cv-238" },
  { label: "Cambodia", value: "kh-855" },
  { label: "Cameroon", value: "cm-237" },
  { label: "Canada", value: "ca-1" },
  { label: "Cayman Islands", value: "ky-1345" },
  { label: "Central African Republic", value: "cf-236" },
  { label: "Chad", value: "td-235" },
  { label: "Chile", value: "cl-56" },
  { label: "China", value: "cn-86" },
  { label: "Colombia", value: "co-57" },
  { label: "Comoros", value: "km-269" },
  { label: "Congo (Republic)", value: "cg-242" },
  { label: "Congo (DRC)", value: "cd-243" },
  { label: "Costa Rica", value: "cr-506" },
  { label: "Côte d'Ivoire", value: "ci-225" },
  { label: "Croatia", value: "hr-385" },
  { label: "Cuba", value: "cu-53" },
  { label: "Curaçao", value: "cw-599" },
  { label: "Cyprus", value: "cy-357" },
  { label: "Czechia", value: "cz-420" },
  { label: "Denmark", value: "dk-45" },
  { label: "Djibouti", value: "dj-253" },
  { label: "Dominica", value: "dm-1767" },
  { label: "Dominican Republic", value: "do-1809" },
  { label: "Ecuador", value: "ec-593" },
  { label: "Egypt", value: "eg-20" },
  { label: "El Salvador", value: "sv-503" },
  { label: "Equatorial Guinea", value: "gq-240" },
  { label: "Eritrea", value: "er-291" },
  { label: "Estonia", value: "ee-372" },
  { label: "Eswatini", value: "sz-268" },
  { label: "Ethiopia", value: "et-251" },
  { label: "Falkland Islands", value: "fk-500" },
  { label: "Faroe Islands", value: "fo-298" },
  { label: "Fiji", value: "fj-679" },
  { label: "Finland", value: "fi-358" },
  { label: "France", value: "fr-33" },
  { label: "French Guiana", value: "gf-594" },
  { label: "French Polynesia", value: "pf-689" },
  { label: "Gabon", value: "ga-241" },
  { label: "Gambia", value: "gm-220" },
  { label: "Georgia", value: "ge-995" },
  { label: "Germany", value: "de-49" },
  { label: "Ghana", value: "gh-233" },
  { label: "Gibraltar", value: "gi-350" },
  { label: "Greece", value: "gr-30" },
  { label: "Greenland", value: "gl-299" },
  { label: "Grenada", value: "gd-1473" },
  { label: "Guadeloupe", value: "gp-590" },
  { label: "Guam", value: "gu-1671" },
  { label: "Guatemala", value: "gt-502" },
  { label: "Guernsey", value: "gg-44" },
  { label: "Guinea", value: "gn-224" },
  { label: "Guinea-Bissau", value: "gw-245" },
  { label: "Guyana", value: "gy-592" },
  { label: "Haiti", value: "ht-509" },
  { label: "Honduras", value: "hn-504" },
  { label: "Hong Kong", value: "hk-852" },
  { label: "Hungary", value: "hu-36" },
  { label: "Iceland", value: "is-354" },
  { label: "India", value: "in-91" },
  { label: "Indonesia", value: "id-62" },
  { label: "Iran", value: "ir-98" },
  { label: "Iraq", value: "iq-964" },
  { label: "Ireland", value: "ie-353" },
  { label: "Isle of Man", value: "im-44" },
  { label: "Israel", value: "il-972" },
  { label: "Italy", value: "it-39" },
  { label: "Jamaica", value: "jm-1876" },
  { label: "Japan", value: "jp-81" },
  { label: "Jersey", value: "je-44" },
  { label: "Jordan", value: "jo-962" },
  { label: "Kazakhstan", value: "kz-7" },
  { label: "Kenya", value: "ke-254" },
  { label: "Kiribati", value: "ki-686" },
  { label: "Kosovo", value: "xk-383" },
  { label: "Kuwait", value: "kw-965" },
  { label: "Kyrgyzstan", value: "kg-996" },
  { label: "Laos", value: "la-856" },
  { label: "Latvia", value: "lv-371" },
  { label: "Lebanon", value: "lb-961" },
  { label: "Lesotho", value: "ls-266" },
  { label: "Liberia", value: "lr-231" },
  { label: "Libya", value: "ly-218" },
  { label: "Liechtenstein", value: "li-423" },
  { label: "Lithuania", value: "lt-370" },
  { label: "Luxembourg", value: "lu-352" },
  { label: "Macau", value: "mo-853" },
  { label: "North Macedonia", value: "mk-389" },
  { label: "Madagascar", value: "mg-261" },
  { label: "Malawi", value: "mw-265" },
  { label: "Malaysia", value: "my-60" },
  { label: "Maldives", value: "mv-960" },
  { label: "Mali", value: "ml-223" },
  { label: "Malta", value: "mt-356" },
  { label: "Marshall Islands", value: "mh-692" },
  { label: "Martinique", value: "mq-596" },
  { label: "Mauritania", value: "mr-222" },
  { label: "Mauritius", value: "mu-230" },
  { label: "Mayotte", value: "yt-262" },
  { label: "Mexico", value: "mx-52" },
  { label: "Micronesia", value: "fm-691" },
  { label: "Moldova", value: "md-373" },
  { label: "Monaco", value: "mc-377" },
  { label: "Mongolia", value: "mn-976" },
  { label: "Montenegro", value: "me-382" },
  { label: "Montserrat", value: "ms-1664" },
  { label: "Morocco", value: "ma-212" },
  { label: "Mozambique", value: "mz-258" },
  { label: "Myanmar", value: "mm-95" },
  { label: "Namibia", value: "na-264" },
  { label: "Nauru", value: "nr-674" },
  { label: "Nepal", value: "np-977" },
  { label: "Netherlands", value: "nl-31" },
  { label: "New Caledonia", value: "nc-687" },
  { label: "New Zealand", value: "nz-64" },
  { label: "Nicaragua", value: "ni-505" },
  { label: "Niger", value: "ne-227" },
  { label: "Nigeria", value: "ng-234" },
  { label: "Niue", value: "nu-683" },
  { label: "Norfolk Island", value: "nf-672" },
  { label: "North Korea", value: "kp-850" },
  { label: "Northern Mariana Islands", value: "mp-1670" },
  { label: "Norway", value: "no-47" },
  { label: "Oman", value: "om-968" },
  { label: "Pakistan", value: "pk-92" },
  { label: "Palau", value: "pw-680" },
  { label: "Palestine", value: "ps-970" },
  { label: "Panama", value: "pa-507" },
  { label: "Papua New Guinea", value: "pg-675" },
  { label: "Paraguay", value: "py-595" },
  { label: "Peru", value: "pe-51" },
  { label: "Philippines", value: "ph-63" },
  { label: "Pitcairn", value: "pn-64" },
  { label: "Poland", value: "pl-48" },
  { label: "Portugal", value: "pt-351" },
  { label: "Puerto Rico", value: "pr-1787" },
  { label: "Qatar", value: "qa-974" },
  { label: "Réunion", value: "re-262" },
  { label: "Romania", value: "ro-40" },
  { label: "Russia", value: "ru-7" },
  { label: "Rwanda", value: "rw-250" },
  { label: "Saint Barthélemy", value: "bl-590" },
  { label: "Saint Helena", value: "sh-290" },
  { label: "Saint Kitts and Nevis", value: "kn-1869" },
  { label: "Saint Lucia", value: "lc-1758" },
  { label: "Saint Martin (French)", value: "mf-590" },
  { label: "Saint Pierre and Miquelon", value: "pm-508" },
  { label: "Saint Vincent and the Grenadines", value: "vc-1784" },
  { label: "Samoa", value: "ws-685" },
  { label: "San Marino", value: "sm-378" },
  { label: "Sao Tomé and Príncipe", value: "st-239" },
  { label: "Saudi Arabia", value: "sa-966" },
  { label: "Senegal", value: "sn-221" },
  { label: "Serbia", value: "rs-381" },
  { label: "Seychelles", value: "sc-248" },
  { label: "Sierra Leone", value: "sl-232" },
  { label: "Singapore", value: "sg-65" },
  { label: "Sint Maarten", value: "sx-1721" },
  { label: "Slovakia", value: "sk-421" },
  { label: "Slovenia", value: "si-386" },
  { label: "Solomon Islands", value: "sb-677" },
  { label: "Somalia", value: "so-252" },
  { label: "South Africa", value: "za-27" },
  { label: "South Georgia & South Sandwich Isls", value: "gs-500" },
  { label: "South Korea", value: "kr-82" },
  { label: "South Sudan", value: "ss-211" },
  { label: "Spain", value: "es-34" },
  { label: "Sri Lanka", value: "lk-94" },
  { label: "Sudan", value: "sd-249" },
  { label: "Suriname", value: "sr-597" },
  { label: "Svalbard and Jan Mayen", value: "sj-47" },
  { label: "Sweden", value: "se-46" },
  { label: "Switzerland", value: "ch-41" },
  { label: "Syria", value: "sy-963" },
  { label: "Taiwan", value: "tw-886" },
  { label: "Tajikistan", value: "tj-992" },
  { label: "Tanzania", value: "tz-255" },
  { label: "Thailand", value: "th-66" },
  { label: "Timor-Leste", value: "tl-670" },
  { label: "Togo", value: "tg-228" },
  { label: "Tokelau", value: "tk-690" },
  { label: "Tonga", value: "to-676" },
  { label: "Trinidad and Tobago", value: "tt-1868" },
  { label: "Tunisia", value: "tn-216" },
  { label: "Turkey", value: "tr-90" },
  { label: "Turkmenistan", value: "tm-993" },
  { label: "Turks and Caicos Islands", value: "tc-1649" },
  { label: "Tuvalu", value: "tv-688" },
  { label: "U.S. Virgin Islands", value: "vi-1340" },
  { label: "Uganda", value: "ug-256" },
  { label: "Ukraine", value: "ua-380" },
  { label: "United Arab Emirates", value: "ae-971" },
  { label: "United Kingdom", value: "gb-44" },
  { label: "United States", value: "us-1" },
  { label: "Uruguay", value: "uy-598" },
  { label: "Uzbekistan", value: "uz-998" },
  { label: "Vanuatu", value: "vu-678" },
  { label: "Vatican City", value: "va-379" },
  { label: "Venezuela", value: "ve-58" },
  { label: "Vietnam", value: "vn-84" },
  { label: "Wallis and Futuna", value: "wf-681" },
  { label: "Western Sahara", value: "eh-212" },
  { label: "Yemen", value: "ye-967" },
  { label: "Zambia", value: "zm-260" },
  { label: "Zimbabwe", value: "zw-263" },
].sort((a, b) => a.label.localeCompare(b.label));
